baseURL: "https://zzsqwq.github.io/academic-pages-demo/" 
languageCode: 'en-us'  # http://www.rssboard.org/rss-language-codes
DefaultContentLanguage: "en" # The default contentlanguage, see languages part.
title: "Zs's Homepage" # default title
theme: "hugo-academia"
canonifyURLs : true # if use absolute path.

languages:
  en:
    languageName: ":uk:"
    weight: 1
    contentDir: content/en
  zh-cn:
    languageName: ":cn:"
    weight: 2
    title: "Zs's Homepage"
    contentDir: content/zh-cn
    params:
      author: "战战硕"
      author_bio: "一名来自西北工业大学的本科生，对机器人及计算机视觉感兴趣。"
      menu:
        Index:
          name: "Index"
          url: /
          weight: 1
        About:
          name: "About"
          url: b/
          weight: 3
        Publications:
          name: "Publications"
          url: "/#Publications"
          weight: 2
        Blog:
          name: "Blog Posts"
          url: https://zzsqwq.cn/
          weight: 4

params:
  author: "Shuo Zhan"
  author_bio: "An undergraduate student in NWPU. Interested in Robotics and CV"
  since: "2019"
  icp: "网ICP备2023114514号"
  avatar: "/images/avatar.png"
  favicon: "/images/favicon.ico"  # Please use .ico format
  menu: # The navigation bar
    Index:
        name: "Index"
        url: /
        weight: 1
    About:
        name: "About"
        url: b/
        weight: 3
    Publications:
        name: "Publications"
        url: "/#Publications"
        weight: 2
    Blog:
        name: "Blog Posts"
        url: "https://zzsqwq.cn/"
        weight: 4

  # The default avatar if params.avatar not set.
  loading_bg:
    flink: /images/profile.png

  # Social Links; 社交链接，不需要的链接直接注释掉
  # Find icons here : https://fontawesome.com/icons/
  # 可以通过 weight 调整显示顺序
  # 图标调用 font-awesome 5.13
  social:
    enable: true
    links:
      Github: 
        icon: fab fa-github 
        url: https://github.com/zzsqwq
        weight: 1
      Telegram:
        icon: fab fa-telegram
        url: https://t.me/zzsqwq
        weight: 2
      Envelope: #E-mail
        icon: fas fa-envelope
        url: mailto:trizsqwq@gmail.com
        weight: 3
      RSS:
        icon: fas fa-rss
        url: "index.xml/"
        weight: 4
      # Weixin: 
      #   icon: fab fa-weixin
      #   url: 
      # QQ: 
      #   icon: fab fa-qq
      #   url:
      # Twitter: 
      #   icon: fab fa-twitter
      #   url: /
      # Facebook: 
      #   icon: fab fa-facebook-square
      #   url:
      # StackOverflow: 
      #   icon: fab fa-stack-overflow
      #   url:
      # Linkedin: 
      #   icon: fab fa-linkedin
      #   url:
      # Weibo: 
      #   icon: fab fa-weibo
      #   url:

  # Additional social_links，额外添加自定义链接，可显示链接名称
  # 可以通过 weight 更改顺序
  e_social:
    enable: true
    links:
      Google Scholar:
        name: Google Scholar
        url:  "/"
        icon: "fas fa-graduation-cap"
        weight: 1
      ORCID:
        name: ORCID
        url: "/"
        icon: "fab fa-orcid"
        weight: 2

  # CV download link
  cv_dl:
    enable: true
    dir: /attaches/CV.pdf
    description: Zs's CV

  # Box-shadow
  # display box-shadow on page or not
  box_shadow:
    enable: false

  # CDN
  # 根据需要自行添加js/css
  # 自定义css可以直接写在user.styl中
  CDN_USE:
    css:
      - /css/style.css
      - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
    js:
      - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
      - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
      - /js/main.js
